version: 2.1
jobs:
  build:
    docker:
      - image: fr3akyphantom/droid-builder:latest
    environment:
      MANIFEST_BRANCH: 'android-9.0'
      # PBRP_BRANCH: '' # optional, if not default 'android-9.0', define other bootable_recovery branch
      VERSION: '3.0.0' # as of now, the current PBRP version
      MAINTAINER: '@Sathamspot (PBRP Team)'
      VENDOR: 'realme'
      CODENAME: 'RMX1901'
      BUILD_LUNCH: 'omni_RMX1901-eng'
      PB_OFFICIAL: 'true'
      CHANGELOG: " - Initial build"
    working_directory: /home/builder/pitchblack
    steps:
      - run:
          name: AIO Build
          command: |
            echo "Set GitAuth Infos"
            git config --global user.email $GitHubMail
            git config --global user.name $GitHubName
            git config --global credential.helper store
            git config --global color.ui true
            wget -q https://raw.githubusercontent.com/PitchBlackRecoveryProject/vendor_utils/pb/build.sh
            source build.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: 'android-9.0'
          context: org-global
